// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpOBTTExcGujydjH3blphzD5vDsd0xXLw',
    appId: '1:99104018643:web:14cccc3e1dc7cbbbce8426',
    messagingSenderId: '99104018643',
    projectId: 'flutter101-tito',
    authDomain: 'flutter101-tito.firebaseapp.com',
    storageBucket: 'flutter101-tito.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvK2pukA7qL8Qv6Hk0F-n7zMgVG2Z7tKA',
    appId: '1:99104018643:android:3286b0429472c7c2ce8426',
    messagingSenderId: '99104018643',
    projectId: 'flutter101-tito',
    storageBucket: 'flutter101-tito.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2ELV9UZXoIF0amGhFZiqhdfSiapNFONk',
    appId: '1:99104018643:ios:585ccd324cdbc2d0ce8426',
    messagingSenderId: '99104018643',
    projectId: 'flutter101-tito',
    storageBucket: 'flutter101-tito.appspot.com',
    iosClientId: '99104018643-tv5k3vtvjaif82r08fofn9frr8eldh8a.apps.googleusercontent.com',
    iosBundleId: 'com.example.titoLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2ELV9UZXoIF0amGhFZiqhdfSiapNFONk',
    appId: '1:99104018643:ios:585ccd324cdbc2d0ce8426',
    messagingSenderId: '99104018643',
    projectId: 'flutter101-tito',
    storageBucket: 'flutter101-tito.appspot.com',
    iosClientId: '99104018643-tv5k3vtvjaif82r08fofn9frr8eldh8a.apps.googleusercontent.com',
    iosBundleId: 'com.example.titoLogin',
  );
}
